# Generated by Django 3.2.9 on 2021-11-08 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highscores', '0002_alter_simpletable_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simplescore',
            options={'verbose_name': 'Simple Highscore Entry', 'verbose_name_plural': 'Simple Highscore Entries'},
        ),
        migrations.AlterModelOptions(
            name='simpletable',
            options={'verbose_name': 'Simple Highscore Table', 'verbose_name_plural': 'Simple Highscore Tables'},
        ),
    ]
