# Generated by Django 3.2.9 on 2021-11-09 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_alter_game_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientKeyPermission',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Clientkey',
            fields=[
                ('key', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('revoked', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
                ('generated', models.DateTimeField(auto_now=True)),
                ('expires', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(default='Unnamed Key', max_length=32)),
                ('details', models.TextField(max_length=1024)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('permissions', models.ManyToManyField(to='clientkeys.ClientKeyPermission')),
            ],
        ),
    ]
