# Generated by Django 3.2.9 on 2021-11-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientkeys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientkey',
            name='prefix',
            field=models.CharField(default='OLDY', editable=False, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientkey',
            name='suffix',
            field=models.CharField(default=1, editable=False, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientkey',
            name='key',
            field=models.CharField(editable=False, max_length=13, primary_key=True, serialize=False),
        ),
    ]
