# Generated by Django 3.2.9 on 2021-11-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientkeys', '0002_auto_20211113_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientkey',
            name='details',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='clientkey',
            name='expires',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='clientkey',
            name='key',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientkey',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='clientkeys.ClientKeyPermission'),
        ),
    ]
