# Generated by Django 3.2.9 on 2021-11-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientkeys', '0005_auto_20211116_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienttoken',
            old_name='token',
            new_name='servertoken',
        ),
        migrations.AddField(
            model_name='clienttoken',
            name='clienttoken',
            field=models.CharField(default='--------', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienttoken',
            name='encoding',
            field=models.CharField(default='sha1', max_length=10),
        ),
    ]
